### ISSUE TITLE
大神，我知道停更了，可是离线安装后，为什么不能开启呢？

### ISSUE THREAD

**Issue by dodofeel** [koolproxy/merlin-koolproxy#10]
大神，我知道停更了，可是离线安装后，为什么不能开启呢？
十分想知道如何单纯的开启，难道开启需要网络验证吗？规则我会自己更新，作者大神如果没法回复了，请各位大神指点下啦！万分感谢！
ac86u，现在的状态是，离线安装完毕后，点提交后，卡在横线那一点了，有办法直接开启吗？再次感谢！

**Comment by sadoneli** [comment]
86U请不要安装本项目插件！
https://koolshare.cn/thread-127878-1-1.html

> 请不要使用离线安装来安装AM380 merlin固件的任何插件，不然肯定会造成问题！！！给RT-AC86U离线安装插件一定要是hnd/axhnd平台的机器（目前包括：RT-AC86U，GT-AC5300，RT-AX88U，GT-AX11000），详情见下文FAQ：Q3

**Comment by dodofeel** [comment]
谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢谢！！！！我去~太感谢了太感谢了！！！！！！！成功解决！太棒了！！！！谢谢谢谢谢谢谢谢谢谢谢谢谢谢！！



------------------ 原始邮件 ------------------
发件人: "sadog"<notifications@github.com>; 
发送时间: 2019年7月2日(星期二) 下午5:10
收件人: "koolproxy/merlin-koolproxy"<merlin-koolproxy@noreply.github.com>; 
抄送: "凯撒奥古斯都"<88005930@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [koolproxy/merlin-koolproxy] 大神，我知道停更了，可是离线安装后，为什么不能开启呢？ (#10)




86U请不要安装本项目插件！
 https://koolshare.cn/thread-127878-1-1.html
  
请不要使用离线安装来安装AM380 merlin固件的任何插件，不然肯定会造成问题！！！给RT-AC86U离线安装插件一定要是hnd/axhnd平台的机器（目前包括：RT-AC86U，GT-AC5300，RT-AX88U，GT-AX11000），详情见下文FAQ：Q3
